# Site settings
title: Vigeo Construction and Consulting
email: joshua@vigeoconstruction.com
description: > Veteran owned and operated home renovation and remodeling company that focuses on homeowner wellness and productivity - we're environmentally focused, using renewable / LEED / WELL standard materials and solutions
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
author: Joshua Coffie
logo: favicon.png

facebook_username: Vigeo-Construction-and-Consulting-251724985766567
nextdoor_username: vigeo-construction-and-consulting-thornton-co

# Build settings
markdown: kramdown

url: "https://vigeoconstruction.com" # the hostname & protocol for site
plugins:
   - jekyll-sitemap
   - jekyll-seo-tag
